### ISSUE TITLE
Profit calculation not accounting for bundle payouts

### ISSUE THREAD

**Issue by benhenryhunter** [OreoMev/mevpanda#1]
After investigating some reports that bloXroute is overpromising on blocks and not paying the bid amount I discovered there is an issue with the calculation of delivered ETH when it comes to blocks where the validator's fee recipient is set as the block's coinbase.

A common strategy to increase the position of an MEV bundle is to include a tip to the block's coinbase address, this happens within an internal transaction and the value of this is not being caught by the script within [this section](https://github.com/OreoMev/mevpanda/blob/main/backend/server.py#L222-L228).

Here is an example slot that this can be viewed:

https://beaconcha.in/slot/5646812

Validator address: 0xe349aaafb737c8d1ab6e05c4ecbf0e9bc62b6495
Bid value: 22020578367839168
Block reward: 21362657685589168
Balance block before: 36891158734711348707 (0x1fff7b9695704dde3)
Balance on block: 36913179313079187875 (0x20045f502c661f9a3)
Balance difference: 22020578367839168

You can see additional transfers within internal transactions here:
https://beaconcha.in/tx/0x9fd9ef2aeff84c9785fede687ea651c6dd9f6018efe2615e5ec06977166292c1#internal-txns

**Comment by OreoMev** [comment]
You are correct,

internal transfers are not included in the calculation. This will be fixed soon.

**Comment by OreoMev** [comment]
Problem solved, once confident that script is correct will upload the new version.
