### ISSUE TITLE
ultra sound styling

### ISSUE THREAD

**Issue by JustinDrake** [OreoMev/mevpanda#2]
Congrats on this useful resource! I suggest making a couple stylistic changes for the ultra sound relay:

* "Ultrasound" -> "ultra sound"
* pink U -> [this image](https://user-images.githubusercontent.com/731743/216462348-841192fc-a9cd-40a7-af18-ff7322734157.png) instead

BTW, please reach out to me on Twitter, Telegram, or Discord. Would love to chat :)

**Comment by OreoMev** [comment]
Hey, 

Changes made, if there is anything else let me know, happy to help :)

**Comment by JustinDrake** [comment]
Thanks!

Feature request: allow individual relays to be turned on and off in the "Builder To Relay" visualisation. For example, it would be cool to only show Flashbots and ultra sound so that I can easily compare the two (without clutter from the other relays).

**Comment by OreoMev** [comment]
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/122867899/217498606-d8e5e5f5-0e4a-42f9-a477-7a385a6a29ed.png">

Done, closing this thread.
